version: "3.8"
services:
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    environment:
      # Optional: set in .env as PUBLIC_BASE_URL=http://<HOST_LAN_IP>:5173 to generate absolute room links for LAN
      PUBLIC_BASE_URL: ${PUBLIC_BASE_URL:-}
    ports:
      - "8000:8000"

  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
      args:
        VITE_API_BASE: ${VITE_API_BASE:-}
        VITE_WS_BASE: ${VITE_WS_BASE:-}
        # Provide your ICE servers JSON here or via .env as VITE_ICE_JSON (single-line JSON). Defaults to [].
        VITE_ICE_JSON: "${VITE_ICE_JSON:-[]}"
        # Optional: force TURN-only routing in restrictive networks ("relay" or "all")
        VITE_ICE_TRANSPORT_POLICY: ${VITE_ICE_TRANSPORT_POLICY:-}
    depends_on:
      - backend
    ports:
      - "5173:80"
