services:
  backend:
    build: ./backend
    container_name: webcall-backend
    ports:
      - "8000:8000"
    environment:
      - PUBLIC_BASE_URL=${PUBLIC_BASE_URL:-http://localhost:5173}
      - LOG_TO_FILE=${LOG_TO_FILE:-false}
      - WS_RETRY_ATTEMPTS=${WS_RETRY_ATTEMPTS:-3}
      - WS_RETRY_DELAY=${WS_RETRY_DELAY:-1.0}
      - WS_MAX_RETRY_DELAY=${WS_MAX_RETRY_DELAY:-30.0}
      - PREVIEW_MAX_BYTES=${PREVIEW_MAX_BYTES:-300000}
      - PREVIEW_TTL_SECONDS=${PREVIEW_TTL_SECONDS:-120}
      - TRUSTED_HOSTS=${TRUSTED_HOSTS:-}
    volumes:
      - ./backend:/app
      - backend_logs:/app/logs
    networks:
      - webcall-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: '0.5'
        reservations:
          memory: 256M
          cpus: '0.25'

  frontend:
    build: 
      context: ./frontend
      args:
        VITE_ICE_JSON: ${VITE_ICE_JSON:-[]}
        VITE_ICE_TRANSPORT_POLICY: ${VITE_ICE_TRANSPORT_POLICY:-all}
    container_name: webcall-frontend
    ports:
      - "5173:80"
      - "8080:8080"  # Nginx status port
    depends_on:
      backend:
        condition: service_healthy
    networks:
      - webcall-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    deploy:
      resources:
        limits:
          memory: 256M
          cpus: '0.25'
        reservations:
          memory: 128M
          cpus: '0.1'

  turn:
    image: coturn/coturn:4.6.2
    container_name: webcall-turn
    ports:
      - "3478:3478"
      - "3478:3478/udp"
      - "50000-50100:50000-50100/udp"
    environment:
      - TURN_USERNAME=${TURN_USERNAME:-user}
      - TURN_PASSWORD=${TURN_PASSWORD:-secret}
      - TURN_REALM=${TURN_REALM:-localhost}
    command: >
      turnserver
      --listening-port=3478
      --listening-ip=0.0.0.0
      --user=${TURN_USERNAME:-user}:${TURN_PASSWORD:-secret}
      --realm=${TURN_REALM:-localhost}
      --min-port=50000
      --max-port=50100
      --fingerprint
      --no-cli
      --log-file=stdout
      --verbose
    networks:
      - webcall-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "nc", "-z", "localhost", "3478"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    deploy:
      resources:
        limits:
          memory: 256M
          cpus: '0.25'
        reservations:
          memory: 128M
          cpus: '0.1'

  # Мониторинг и логирование
  prometheus:
    image: prom/prometheus:latest
    container_name: webcall-prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
      - '--storage.tsdb.retention.time=200h'
      - '--web.enable-lifecycle'
    networks:
      - webcall-network
    restart: unless-stopped
    profiles:
      - monitoring

  grafana:
    image: grafana/grafana:latest
    container_name: webcall-grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_PASSWORD:-admin}
    volumes:
      - grafana_data:/var/lib/grafana
      - ./monitoring/grafana/dashboards:/etc/grafana/provisioning/dashboards
      - ./monitoring/grafana/datasources:/etc/grafana/provisioning/datasources
    networks:
      - webcall-network
    restart: unless-stopped
    profiles:
      - monitoring

  # Логирование
  loki:
    image: grafana/loki:latest
    container_name: webcall-loki
    ports:
      - "3100:3100"
    volumes:
      - loki_data:/loki
    command: -config.file=/etc/loki/local-config.yaml
    networks:
      - webcall-network
    restart: unless-stopped
    profiles:
      - logging

  promtail:
    image: grafana/promtail:latest
    container_name: webcall-promtail
    volumes:
      - ./monitoring/promtail-config.yml:/etc/promtail/config.yml
      - /var/log:/var/log
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
    command: -config.file=/etc/promtail/config.yml
    networks:
      - webcall-network
    restart: unless-stopped
    profiles:
      - logging

volumes:
  backend_logs:
  prometheus_data:
  grafana_data:
  loki_data:

networks:
  webcall-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16
