version: "3.8"
services:
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    ports:
      - "8000:8000"
    environment:
      - PUBLIC_BASE_URL=${PUBLIC_BASE_URL:-http://localhost:5173}
      - LOG_TO_FILE=${LOG_TO_FILE:-false}
      - WS_RETRY_ATTEMPTS=${WS_RETRY_ATTEMPTS:-3}
      - WS_RETRY_DELAY=${WS_RETRY_DELAY:-1.0}
      - WS_MAX_RETRY_DELAY=${WS_MAX_RETRY_DELAY:-30.0}
      - PREVIEW_MAX_BYTES=${PREVIEW_MAX_BYTES:-300000}
      - PREVIEW_TTL_SECONDS=${PREVIEW_TTL_SECONDS:-120}
      - TRUSTED_HOSTS=${TRUSTED_HOSTS:-}

  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
      args:
        VITE_API_BASE: ${VITE_API_BASE:-}
        VITE_WS_BASE: ${VITE_WS_BASE:-}
        VITE_ICE_JSON: ${VITE_ICE_JSON:-[]}
        VITE_ICE_TRANSPORT_POLICY: ${VITE_ICE_TRANSPORT_POLICY:-all}
    ports:
      - "5173:80"
    depends_on:
      - backend

  turn:
    image: coturn/coturn:4.6.2
    container_name: webcall-turn
    ports:
      - "3478:3478"
      - "3478:3478/udp"
      - "50000-50100:50000-50100/udp"
    environment:
      - TURN_USERNAME=${TURN_USERNAME:-user}
      - TURN_PASSWORD=${TURN_PASSWORD:-secret}
      - TURN_REALM=${TURN_REALM:-localhost}
    command: >
      turnserver
      --listening-port=3478
      --listening-ip=0.0.0.0
      --user=${TURN_USERNAME:-user}:${TURN_PASSWORD:-secret}
      --realm=${TURN_REALM:-localhost}
      --min-port=50000
      --max-port=50100
      --fingerprint
      --no-cli
      --log-file=stdout
      --verbose
